// AUTO-GENERATED by scripts/compress-examples.mjs — do not edit by hand.
export interface ExampleImage {
  src: string;
  alt: string;
}

export const CHICHI_TIKTOK_URL = "https://www.tiktok.com/@chichi.kelinci";

export const CHICHI_EXAMPLES: ExampleImage[] = [
  {
    "src": "/examples/chichi/chichi-kelinci-1.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-1"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-2.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-2"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-3.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-3"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-4.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-4"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-5.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-5"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-6.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-6"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-7.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-7"
  },
  {
    "src": "/examples/chichi/chichi-kelinci-8.webp",
    "alt": "Chichi Kelinci — chichi-kelinci-8"
  }
];

export const OTHER_EXAMPLES: ExampleImage[] = [
  {
    "src": "/examples/lainnya/hasil-a1.webp",
    "alt": "Hasil — hasil-a1"
  },
  {
    "src": "/examples/lainnya/hasil-a2.webp",
    "alt": "Hasil — hasil-a2"
  },
  {
    "src": "/examples/lainnya/hasil-b1.webp",
    "alt": "Hasil — hasil-b1"
  },
  {
    "src": "/examples/lainnya/hasil-b2.webp",
    "alt": "Hasil — hasil-b2"
  },
  {
    "src": "/examples/lainnya/hasil-c1.webp",
    "alt": "Hasil — hasil-c1"
  },
  {
    "src": "/examples/lainnya/hasil-c2.webp",
    "alt": "Hasil — hasil-c2"
  }
];
